### ISSUE TITLE
CWD timeslider map

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#66]
- [x] funny aspect ratio in the X button below the legend
- [x] dot size is not all 4.5
- [x] Source errors (see console logs on the page)

We have a request to publish this map on sva's external website and I would like to at least fix point 2 and 3 above before doing that. 

Also perhaps point 3 requires the updating to a newer jquery. I am not against using a remote source.

**Comment by hykim3594** [comment]
Fixed point 1 and 2. 

I have no idea about point 3 because I didn't get any error..

**Comment by trosendal** [comment]
great! I'll check the console log on that map to see if I still get the warning in firefox. I have not yet looked at the result but suspect it will be 'awesome' with the addition of the new css :)

**Comment by hykim3594** [comment]
If the error you mentioned for point 3 meant violation warnings, then I got the same warnings. 

To get rid of them, I updated the jquery version and modified a bit from the original file: line 5038.
Also, I added a remote source to remove the same warnings for leaflet.js.

**Comment by hykim3594** [comment]
Updated leaflet.js, easy-button.js, and jquery.js and included a new font-awesome.css but the map on the external website does not seem to reflect the update. There should be no errors or warnings in the console box but it still shows.

**Comment by trosendal** [comment]
I think you were probably looking for the map here?:
https://www.sva.se/Maps/CWD/map.html

Your modifications are deployed here:
https://www.sva.se/Maps/CWD_timeslider/map.html

It looks good I think :+1: I will discuss with Sara Stoltz about making a test page for it to replace this page:

https://www.sva.se/smittlage/karta-over-cwdavmagringssjuka

**Comment by trosendal** [comment]
One small bug:
![screenshot from 2018-11-05 08-41-16](https://user-images.githubusercontent.com/3989235/47984359-b343fa80-e0d6-11e8-9384-ce93b24ae5a4.png)
When I click to hide the legend I get this icon. 

looks like something to do with this css class: 'fa-info-circle fa-lg'

**Comment by hykim3594** [comment]
Fixed it.

**Comment by trosendal** [comment]
I'll close now I think. We can reopen the issue if needed but for now we can push it on to KOM to figure out how to integrate with their system to publish
